### ISSUE TITLE
Question about split dataloader into multi-gpus

### ISSUE THREAD

**Issue by YUHANG-Ma** [lucidrains/DALLE2-pytorch#184]
Hi, I met an issue that I rewrite the dataloder to fit my data. It could be trained well through 1 GPU. But when I set accelerate config to have 8-GPU training. I found the model is already on 8 GPUs but it seems the dataloader is not splited to 8 GPUs which causes the training process stucked. 
![image](https://user-images.githubusercontent.com/72591225/177165559-82bd7c92-079a-4880-96c4-901bc4f6783f.png)
I found the variable "rank" in the create dataloader. May I ask where we use it? I couldn't find it in other places. 
![image](https://user-images.githubusercontent.com/72591225/177165760-def56a15-7c1c-49c8-b204-87a49144432c.png)
![image](https://user-images.githubusercontent.com/72591225/177165902-0b8658dc-72fa-4d02-922e-2412ffef0e78.png)

I tried to print something to see where it stucks. I  thought it stucks at the sum process. And if it is trained with multi-GPU, each content should be print 8 times I think. So I try to find out what happened in my dataloader. Here is my dataloader:
![image](https://user-images.githubusercontent.com/72591225/177166146-11be8da9-1b2b-4618-b3e4-fa3e51598411.png)
![image](https://user-images.githubusercontent.com/72591225/177166362-99aeb53a-71b5-41c9-bfad-50fed975b850.png)

I just change the create_image_embedding_dataloader in dataloader.py and didn't change the code in train_decoder.py. I am confused why this could happen.

**Comment by YUHANG-Ma** [comment]
Hi, I solved this problem. It seems to be the problem of the machine. I changed another machine and it works well. So I close this issue as it is solved.
