### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by KathyGCY** [lucidrains/DALLE2-pytorch#233]
This is the code I'm running in jupyter notebook on a mac
>import torch
>from dalle2_pytorch import DALLE2, DiffusionPriorNetwork, DiffusionPrior, Unet, Decoder, CLIP

>clip = CLIP(
    dim_text = 512,
    dim_image = 512,
    dim_latent = 512,
    num_text_tokens = 49408,
    text_enc_depth = 6,
    text_seq_len = 256,
    text_heads = 8,
    visual_enc_depth = 6,
    visual_image_size = 256,
    visual_patch_size = 32,
    visual_heads = 8
).cuda()

And this happened:
<img width="520" alt="Screen Shot 2022-08-19 at 2 46 48 PM" src="https://user-images.githubusercontent.com/14912791/185686730-4d5b1128-dda2-448a-86ca-6f5621012e53.png">

**Comment by antonioortegajr** [comment]
Removing All the  .cuda() from the code should get the code going and not trying to get GPU involved as that isn't supported on Mac.

**Comment by Jorginthesage** [comment]
Can confirm this works on Windows 10 and MacOS Catalina.
